//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhosOn.Library.LogonAccountingServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogonEvent", Namespace="http://it.bmc.uu.se/whoson")]
    [System.SerializableAttribute()]
    public partial class LogonEvent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EventIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HwAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkstationField;
        
        private System.DateTime StartTimeField;
        
        private System.DateTime EndTimeField;
        
        private int FirstIDField;
        
        private int LastIDField;
        
        private int LimitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EventID {
            get {
                return this.EventIDField;
            }
            set {
                if ((this.EventIDField.Equals(value) != true)) {
                    this.EventIDField = value;
                    this.RaisePropertyChanged("EventID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Domain {
            get {
                return this.DomainField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                    this.DomainField = value;
                    this.RaisePropertyChanged("Domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HwAddress {
            get {
                return this.HwAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HwAddressField, value) != true)) {
                    this.HwAddressField = value;
                    this.RaisePropertyChanged("HwAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IpAddress {
            get {
                return this.IpAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IpAddressField, value) != true)) {
                    this.IpAddressField = value;
                    this.RaisePropertyChanged("IpAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Hostname {
            get {
                return this.HostnameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostnameField, value) != true)) {
                    this.HostnameField = value;
                    this.RaisePropertyChanged("Hostname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Workstation {
            get {
                return this.WorkstationField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkstationField, value) != true)) {
                    this.WorkstationField = value;
                    this.RaisePropertyChanged("Workstation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int FirstID {
            get {
                return this.FirstIDField;
            }
            set {
                if ((this.FirstIDField.Equals(value) != true)) {
                    this.FirstIDField = value;
                    this.RaisePropertyChanged("FirstID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int LastID {
            get {
                return this.LastIDField;
            }
            set {
                if ((this.LastIDField.Equals(value) != true)) {
                    this.LastIDField = value;
                    this.RaisePropertyChanged("LastID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int Limit {
            get {
                return this.LimitField;
            }
            set {
                if ((this.LimitField.Equals(value) != true)) {
                    this.LimitField = value;
                    this.RaisePropertyChanged("Limit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogonEventMatch", Namespace="http://it.bmc.uu.se/whoson")]
    public enum LogonEventMatch : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Before = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Between = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        After = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exact = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Closed = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://it.bmc.uu.se/whoson", ConfigurationName="LogonAccountingServiceReference.LogonAccountingServiceSoap")]
    public interface LogonAccountingServiceSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://it.bmc.uu.se/whoson is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://it.bmc.uu.se/whoson/CreateLogonEvent", ReplyAction="*")]
        WhosOn.Library.LogonAccountingServiceReference.CreateLogonEventResponse CreateLogonEvent(WhosOn.Library.LogonAccountingServiceReference.CreateLogonEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.bmc.uu.se/whoson/CloseLogonEvent", ReplyAction="*")]
        void CloseLogonEvent(int eventID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://it.bmc.uu.se/whoson/DeleteLogonEvent", ReplyAction="*")]
        void DeleteLogonEvent(int eventID);
        
        // CODEGEN: Generating message contract since element name user from namespace http://it.bmc.uu.se/whoson is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://it.bmc.uu.se/whoson/FindLogonEvent", ReplyAction="*")]
        WhosOn.Library.LogonAccountingServiceReference.FindLogonEventResponse FindLogonEvent(WhosOn.Library.LogonAccountingServiceReference.FindLogonEventRequest request);
        
        // CODEGEN: Generating message contract since element name filter from namespace http://it.bmc.uu.se/whoson is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://it.bmc.uu.se/whoson/FindLogonEvents", ReplyAction="*")]
        WhosOn.Library.LogonAccountingServiceReference.FindLogonEventsResponse FindLogonEvents(WhosOn.Library.LogonAccountingServiceReference.FindLogonEventsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateLogonEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateLogonEvent", Namespace="http://it.bmc.uu.se/whoson", Order=0)]
        public WhosOn.Library.LogonAccountingServiceReference.CreateLogonEventRequestBody Body;
        
        public CreateLogonEventRequest() {
        }
        
        public CreateLogonEventRequest(WhosOn.Library.LogonAccountingServiceReference.CreateLogonEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.bmc.uu.se/whoson")]
    public partial class CreateLogonEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string domain;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string computer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hwaddr;
        
        public CreateLogonEventRequestBody() {
        }
        
        public CreateLogonEventRequestBody(string user, string domain, string computer, string hwaddr) {
            this.user = user;
            this.domain = domain;
            this.computer = computer;
            this.hwaddr = hwaddr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateLogonEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateLogonEventResponse", Namespace="http://it.bmc.uu.se/whoson", Order=0)]
        public WhosOn.Library.LogonAccountingServiceReference.CreateLogonEventResponseBody Body;
        
        public CreateLogonEventResponse() {
        }
        
        public CreateLogonEventResponse(WhosOn.Library.LogonAccountingServiceReference.CreateLogonEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.bmc.uu.se/whoson")]
    public partial class CreateLogonEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateLogonEventResult;
        
        public CreateLogonEventResponseBody() {
        }
        
        public CreateLogonEventResponseBody(int CreateLogonEventResult) {
            this.CreateLogonEventResult = CreateLogonEventResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindLogonEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindLogonEvent", Namespace="http://it.bmc.uu.se/whoson", Order=0)]
        public WhosOn.Library.LogonAccountingServiceReference.FindLogonEventRequestBody Body;
        
        public FindLogonEventRequest() {
        }
        
        public FindLogonEventRequest(WhosOn.Library.LogonAccountingServiceReference.FindLogonEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.bmc.uu.se/whoson")]
    public partial class FindLogonEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string domain;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string computer;
        
        public FindLogonEventRequestBody() {
        }
        
        public FindLogonEventRequestBody(string user, string domain, string computer) {
            this.user = user;
            this.domain = domain;
            this.computer = computer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindLogonEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindLogonEventResponse", Namespace="http://it.bmc.uu.se/whoson", Order=0)]
        public WhosOn.Library.LogonAccountingServiceReference.FindLogonEventResponseBody Body;
        
        public FindLogonEventResponse() {
        }
        
        public FindLogonEventResponse(WhosOn.Library.LogonAccountingServiceReference.FindLogonEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.bmc.uu.se/whoson")]
    public partial class FindLogonEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WhosOn.Library.LogonAccountingServiceReference.LogonEvent FindLogonEventResult;
        
        public FindLogonEventResponseBody() {
        }
        
        public FindLogonEventResponseBody(WhosOn.Library.LogonAccountingServiceReference.LogonEvent FindLogonEventResult) {
            this.FindLogonEventResult = FindLogonEventResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindLogonEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindLogonEvents", Namespace="http://it.bmc.uu.se/whoson", Order=0)]
        public WhosOn.Library.LogonAccountingServiceReference.FindLogonEventsRequestBody Body;
        
        public FindLogonEventsRequest() {
        }
        
        public FindLogonEventsRequest(WhosOn.Library.LogonAccountingServiceReference.FindLogonEventsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.bmc.uu.se/whoson")]
    public partial class FindLogonEventsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WhosOn.Library.LogonAccountingServiceReference.LogonEvent filter;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public WhosOn.Library.LogonAccountingServiceReference.LogonEventMatch match;
        
        public FindLogonEventsRequestBody() {
        }
        
        public FindLogonEventsRequestBody(WhosOn.Library.LogonAccountingServiceReference.LogonEvent filter, WhosOn.Library.LogonAccountingServiceReference.LogonEventMatch match) {
            this.filter = filter;
            this.match = match;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindLogonEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindLogonEventsResponse", Namespace="http://it.bmc.uu.se/whoson", Order=0)]
        public WhosOn.Library.LogonAccountingServiceReference.FindLogonEventsResponseBody Body;
        
        public FindLogonEventsResponse() {
        }
        
        public FindLogonEventsResponse(WhosOn.Library.LogonAccountingServiceReference.FindLogonEventsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://it.bmc.uu.se/whoson")]
    public partial class FindLogonEventsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WhosOn.Library.LogonAccountingServiceReference.LogonEvent> FindLogonEventsResult;
        
        public FindLogonEventsResponseBody() {
        }
        
        public FindLogonEventsResponseBody(System.Collections.Generic.List<WhosOn.Library.LogonAccountingServiceReference.LogonEvent> FindLogonEventsResult) {
            this.FindLogonEventsResult = FindLogonEventsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogonAccountingServiceSoapChannel : WhosOn.Library.LogonAccountingServiceReference.LogonAccountingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogonAccountingServiceSoapClient : System.ServiceModel.ClientBase<WhosOn.Library.LogonAccountingServiceReference.LogonAccountingServiceSoap>, WhosOn.Library.LogonAccountingServiceReference.LogonAccountingServiceSoap {
        
        public LogonAccountingServiceSoapClient() {
        }
        
        public LogonAccountingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogonAccountingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogonAccountingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogonAccountingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhosOn.Library.LogonAccountingServiceReference.CreateLogonEventResponse WhosOn.Library.LogonAccountingServiceReference.LogonAccountingServiceSoap.CreateLogonEvent(WhosOn.Library.LogonAccountingServiceReference.CreateLogonEventRequest request) {
            return base.Channel.CreateLogonEvent(request);
        }
        
        public int CreateLogonEvent(string user, string domain, string computer, string hwaddr) {
            WhosOn.Library.LogonAccountingServiceReference.CreateLogonEventRequest inValue = new WhosOn.Library.LogonAccountingServiceReference.CreateLogonEventRequest();
            inValue.Body = new WhosOn.Library.LogonAccountingServiceReference.CreateLogonEventRequestBody();
            inValue.Body.user = user;
            inValue.Body.domain = domain;
            inValue.Body.computer = computer;
            inValue.Body.hwaddr = hwaddr;
            WhosOn.Library.LogonAccountingServiceReference.CreateLogonEventResponse retVal = ((WhosOn.Library.LogonAccountingServiceReference.LogonAccountingServiceSoap)(this)).CreateLogonEvent(inValue);
            return retVal.Body.CreateLogonEventResult;
        }
        
        public void CloseLogonEvent(int eventID) {
            base.Channel.CloseLogonEvent(eventID);
        }
        
        public void DeleteLogonEvent(int eventID) {
            base.Channel.DeleteLogonEvent(eventID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhosOn.Library.LogonAccountingServiceReference.FindLogonEventResponse WhosOn.Library.LogonAccountingServiceReference.LogonAccountingServiceSoap.FindLogonEvent(WhosOn.Library.LogonAccountingServiceReference.FindLogonEventRequest request) {
            return base.Channel.FindLogonEvent(request);
        }
        
        public WhosOn.Library.LogonAccountingServiceReference.LogonEvent FindLogonEvent(string user, string domain, string computer) {
            WhosOn.Library.LogonAccountingServiceReference.FindLogonEventRequest inValue = new WhosOn.Library.LogonAccountingServiceReference.FindLogonEventRequest();
            inValue.Body = new WhosOn.Library.LogonAccountingServiceReference.FindLogonEventRequestBody();
            inValue.Body.user = user;
            inValue.Body.domain = domain;
            inValue.Body.computer = computer;
            WhosOn.Library.LogonAccountingServiceReference.FindLogonEventResponse retVal = ((WhosOn.Library.LogonAccountingServiceReference.LogonAccountingServiceSoap)(this)).FindLogonEvent(inValue);
            return retVal.Body.FindLogonEventResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WhosOn.Library.LogonAccountingServiceReference.FindLogonEventsResponse WhosOn.Library.LogonAccountingServiceReference.LogonAccountingServiceSoap.FindLogonEvents(WhosOn.Library.LogonAccountingServiceReference.FindLogonEventsRequest request) {
            return base.Channel.FindLogonEvents(request);
        }
        
        public System.Collections.Generic.List<WhosOn.Library.LogonAccountingServiceReference.LogonEvent> FindLogonEvents(WhosOn.Library.LogonAccountingServiceReference.LogonEvent filter, WhosOn.Library.LogonAccountingServiceReference.LogonEventMatch match) {
            WhosOn.Library.LogonAccountingServiceReference.FindLogonEventsRequest inValue = new WhosOn.Library.LogonAccountingServiceReference.FindLogonEventsRequest();
            inValue.Body = new WhosOn.Library.LogonAccountingServiceReference.FindLogonEventsRequestBody();
            inValue.Body.filter = filter;
            inValue.Body.match = match;
            WhosOn.Library.LogonAccountingServiceReference.FindLogonEventsResponse retVal = ((WhosOn.Library.LogonAccountingServiceReference.LogonAccountingServiceSoap)(this)).FindLogonEvents(inValue);
            return retVal.Body.FindLogonEventsResult;
        }
    }
}
